services:
  postgres_user:
    image: postgres:15
    container_name: postgres_user
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    volumes:
      - pgdata_users:/var/lib/postgresql/data

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis-users:
    image: redis:7
    container_name: redis-users
    ports:
      - "6379:6379"
    volumes:
      - redisdata_user:/data

  redis-notifications:
    image: redis:7
    container_name: redis-notifications
    ports:
      - "6380:6379"
    volumes:
      - redisdata_notification:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      KAFKA_NUM_PARTITIONS: 1  # Дефолтное количество партиций для новых топиков
      KAFKA_LOG_RETENTION_MS: -1  # Отключаем удаление логов (для тестов)
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/data

volumes:
  pgdata_users:
  mongodb_data:
  redisdata_user:
  redisdata_notification:
  kafka_data:
