spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URI}
          username: ${CONFIG_REPO_USER}
          password: ${GITHUB_PASSWORD}
          clone-on-start: true
server:
  port: 8888
